baseURL = 'https://blog.junjia.fun/'
languageCode = 'zh-cn'
title = 'Junjia 的博客'
theme = 'PaperMod'

defaultContentLanguage = 'zh'

enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = 'production'
description = 'My homepage: https://github.com/huangjunjia'
author = 'Junjia Huang'
defaultTheme = 'auto'
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
UseHugoToc = true
comments = false
showtoc = true
tocopen = true

[params.homeInfoParams]
Title = 'Junjia'
Content = '一个微小的、不断学习的前端。'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/huangjunjia'